# Add 'status - has pull prequest' label to all PRs
status - has pull prequest:
- "**"

# Add 'pr - needs testing' label to all PRs
pr - needs testing:
- "**"

# Add 'pr - needs code review' label to all PRs
pr - needs code review:
- "**"
