name: Labeler
on: 
  pull_request:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/backdropcms-labeler.yml
